### PR TITLE
Removing data modifiers

### PR DESCRIPTION
**Pull request by rosswilson**
We don't need the data modifiers anymore, since we now shim `JSON.{parse,stringify}`.

### CODE REVIEW

**Comment by dhurrell** [comment]
Is it useful to maintain this information as a "capability", even if makes no difference at a code level? :trollface:

I get the feeling it isn't reliably accurate, but it might be better than nothing for debugging weird issues with older devices, spotting patterns of performance issues, etc? I don't feel strongly about it though!

**Comment by subsidel** [comment]
Not really no. We have been saying for over a year now that you must have at least es5 for TAL, so the JSON methods must always be present. Also this forces device to load code they aren't ever using :/

**Comment by dhurrell** [comment]
Sorry, to clarify, I meant: is it worth putting "native JSON" in the `capabilities` array?

**Comment by subsidel** [comment]
I don't think so as TAL is no longer concerned by whether or not a device implements it in browser or via polyfill.

**Pull request merged**
